"""initial migration

Revision ID: 2613f1f26afc
Revises: 7572b820b141
Create Date: 2026-09-04 12:07:40.710509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2613f1f26afc'
down_revision: Union[str, Sequence[str], None] = '7572b820b141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('permission_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['share_id'], ['sharelink.share_id'], ),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.drop_column('sharelink', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sharelink', sa.Column('email', mysql.VARCHAR(length=225), nullable=False))
    op.drop_table('permission')
    # ### end Alembic commands ###
