"""initial migration

Revision ID: 2ae04d0a5d94
Revises: 
Create Date: 2026-08-27 13:15:01.837979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ae04d0a5d94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('uploads', sa.Column('file_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'uploads', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'uploads', 'files', ['file_id'], ['file_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploads', type_='foreignkey')
    op.drop_constraint(None, 'uploads', type_='foreignkey')
    op.drop_column('uploads', 'file_id')
    op.drop_column('uploads', 'user_id')
    # ### end Alembic commands ###
