"""initial migration

Revision ID: 5cf6357814ec
Revises: d460856de574
Create Date: 2026-09-10 13:22:24.809020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5cf6357814ec'
down_revision: Union[str, Sequence[str], None] = 'd460856de574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sharelink', 'file_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('sharelink_ibfk_1'), 'sharelink', type_='foreignkey')
    op.create_foreign_key(None, 'sharelink', 'files', ['file_id'], ['file_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sharelink', type_='foreignkey')
    op.create_foreign_key(op.f('sharelink_ibfk_1'), 'sharelink', 'files', ['file_id'], ['file_id'])
    op.alter_column('sharelink', 'file_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
