"""initial migration

Revision ID: 614624412bdf
Revises: a69809999991
Create Date: 2026-09-30 16:50:27.599114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '614624412bdf'
down_revision: Union[str, Sequence[str], None] = 'a69809999991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sharelink', 'token_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sharelink', sa.Column('token_hash', mysql.VARCHAR(length=128), nullable=False))
    op.drop_constraint(None, 'sharelink', type_='unique')
    op.drop_column('sharelink', 'token')
    op.create_table('resetpassword',
    sa.Column('token_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_hash', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('resetpassword_ibfk_1')),
    sa.PrimaryKeyConstraint('token_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
