"""initial migration

Revision ID: 7572b820b141
Revises: d5ed8da2ddac
Create Date: 2026-09-04 11:54:52.578374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7572b820b141'
down_revision: Union[str, Sequence[str], None] = 'd5ed8da2ddac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sharelink', sa.Column('email', sa.String(length=225), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sharelink', 'email')
    # ### end Alembic commands ###
