"""initial migration

Revision ID: 78c98f801c22
Revises: 2ae04d0a5d94
Create Date: 2026-08-27 13:59:45.118609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '78c98f801c22'
down_revision: Union[str, Sequence[str], None] = '2ae04d0a5d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('files', sa.Column('file_name', sa.String(length=255), nullable=False))
    op.add_column('files', sa.Column('password_protected', sa.Boolean(), nullable=False))
    op.add_column('files', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('files', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'files', 'users', ['user_id'], ['user_id'])
    op.drop_column('files', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'deleted_at')
    op.drop_column('files', 'updated_at')
    op.drop_column('files', 'password_protected')
    op.drop_column('files', 'file_name')
    op.drop_column('files', 'user_id')
    # ### end Alembic commands ###
