"""initial migration

Revision ID: 7e51b0f6f1e2
Revises: 614624412bdf
Create Date: 2026-09-30 17:53:30.326047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e51b0f6f1e2'
down_revision: Union[str, Sequence[str], None] = '614624412bdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sharelink', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sharelink', type_='unique')
    # ### end Alembic commands ###
