"""initial migration

Revision ID: 907fc297a690
Revises: bf58cfdf5d58
Create Date: 2026-09-02 13:32:30.876504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '907fc297a690'
down_revision: Union[str, Sequence[str], None] = 'bf58cfdf5d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'folder_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'folder_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
