"""initial migration

Revision ID: 9981d57aec48
Revises: 78c98f801c22
Create Date: 2026-09-01 11:03:59.964273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9981d57aec48'
down_revision: Union[str, Sequence[str], None] = '78c98f801c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('folder_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'files', 'folder', ['folder_id'], ['folder_id'])
    op.add_column('folder', sa.Column('parent_folder_id', sa.Integer(), nullable=True))
    op.add_column('folder', sa.Column('child_folder_id', sa.Integer(), nullable=True))
    op.add_column('folder', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('folder_ibfk_1'), 'folder', type_='foreignkey')
    op.create_foreign_key(None, 'folder', 'folder', ['child_folder_id'], ['folder_id'])
    op.create_foreign_key(None, 'folder', 'folder', ['parent_folder_id'], ['folder_id'])
    op.drop_column('folder', 'parent_folder')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder', sa.Column('parent_folder', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'folder', type_='foreignkey')
    op.drop_constraint(None, 'folder', type_='foreignkey')
    op.create_foreign_key(op.f('folder_ibfk_1'), 'folder', 'folder', ['parent_folder'], ['folder_id'])
    op.drop_column('folder', 'updated_at')
    op.drop_column('folder', 'child_folder_id')
    op.drop_column('folder', 'parent_folder_id')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'folder_id')
    # ### end Alembic commands ###
