"""initial migration

Revision ID: a11a23148177
Revises: 2613f1f26afc
Create Date: 2026-09-08 11:26:30.102061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a11a23148177'
down_revision: Union[str, Sequence[str], None] = '2613f1f26afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('chunk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_table('vectors',
    sa.Column('vector_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], ),
    sa.PrimaryKeyConstraint('vector_id')
    )
    op.drop_table('vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vector',
    sa.Column('vector_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], name=op.f('vector_ibfk_1')),
    sa.PrimaryKeyConstraint('vector_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('vectors')
    op.drop_table('chunks')
    # ### end Alembic commands ###
