"""initial migration

Revision ID: b1dd4cfe72b5
Revises: 907fc297a690
Create Date: 2026-09-03 10:59:41.149952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1dd4cfe72b5'
down_revision: Union[str, Sequence[str], None] = '907fc297a690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('is_indexed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'is_indexed')
    # ### end Alembic commands ###
