"""initial migration

Revision ID: bf58cfdf5d58
Revises: 9981d57aec48
Create Date: 2026-09-01 11:08:39.343827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bf58cfdf5d58'
down_revision: Union[str, Sequence[str], None] = '9981d57aec48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('folder_ibfk_1'), 'folder', type_='foreignkey')
    op.drop_column('folder', 'child_folder_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder', sa.Column('child_folder_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('folder_ibfk_1'), 'folder', 'folder', ['child_folder_id'], ['folder_id'])
    # ### end Alembic commands ###
