"""initial migration

Revision ID: d460856de574
Revises: a11a23148177
Create Date: 2026-09-08 12:56:15.257369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd460856de574'
down_revision: Union[str, Sequence[str], None] = 'a11a23148177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vectors', sa.Column('file_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('vectors_ibfk_1'), 'vectors', type_='foreignkey')
    op.create_foreign_key(None, 'vectors', 'files', ['file_id'], ['file_id'])
    op.drop_column('vectors', 'chunk_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vectors', sa.Column('chunk_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vectors', type_='foreignkey')
    op.create_foreign_key(op.f('vectors_ibfk_1'), 'vectors', 'chunks', ['chunk_id'], ['chunk_id'])
    op.drop_column('vectors', 'file_id')
    # ### end Alembic commands ###
